# docker-compose.production.yml
version: '3'

volumes:
  pg_data_production:
  static_volume:
  foodgram-project-react_static:
  media:


services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: creee9/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: creee9/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: creee9/foodgram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/app/media/
    ports:
      - 8000:80