# version: '3.3'
# services:

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     volumes:
#       - ./frontend/:/app/result_build/

#   nginx:
#     image: nginx:1.19.3
#     ports:
#       - "80:80"
#     volumes:
#       - /nginx.conf:/etc/nginx/conf.d/default.conf
#       - ./frontend/build:/usr/share/nginx/html/
#       - ./docs/:/usr/share/nginx/html/api/docs/



# version: '3.3'

# volumes:
#   pg_data:

# services:

#   db:
#     image: postgres:13.10
#     env_file: .env
#     volumes:
#       - pg_data:/var/lib/postgresql/data

#   backend:
#     build: ./backend/
#     env_file: .env
#     depends_on:
#       - db

#   frontend:
#     build:
#       context: ./frontend/
#       dockerfile: Dockerfile
#     volumes:
#       - ./frontend/:/app/result_build/

#   gateway:
#     build: ./gateway/
#     ports:
#       - 8000:80 

#   # nginx:
#   #   image: nginx:1.19.3
#   #   ports:
#   #     - "80:80"
#   #   volumes:
#   #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
#   #     - ./frontend/build:/usr/share/nginx/html/
#   #     - ./docs/:/usr/share/nginx/html/api/docs/





# version: '3.8'
# services:

#   db:
#     image: postgres:13.0-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - ./.env

#   backend:
#     image: xofmdo/foodgram_back:latest
#     restart: always
#     volumes:
#       - data_value:/app/data/
#       - static_value:/app/static/
#       - media_value:/app/media/
#     depends_on:
#       - db
#     env_file:
#       - ./.env

#   frontend:
#     image: xofmdo/foodgram_front:latest
#     volumes:
#       - ../frontend/:/app/result_build/
#     depends_on:
#       - backend

#   nginx:
#     image: nginx:1.19.3
#     ports:
#       - 80:80
#     volumes:
#       - ./default.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
#       - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
#       - static_value:/var/html/static/
#       - media_value:/var/html/media/
#     depends_on:
#       - frontend

# volumes:
#   postgres_data:
#   static_value:
#   media_value:
#   data_value:



version: '3'

volumes:
  pg_data:
  static:
  foodgram-project-react_static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
      - media:/app/media/
    ports:
      - 8000:80
