# Generated by Django 4.2.5 on 2023-10-10 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_options_remove_ingredient_name_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#569914', help_text='Введите цвет тега в формате HEX', max_length=7, validators=[django.core.validators.RegexValidator(message='Необходимо указать цвет в кодировке HEX.', regex='#([a-fA-F0-9]){3, 6}')]),
        ),
    ]
