# Generated by Django 4.2.5 on 2023-10-10 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#569914', help_text='Введите цвет тега в формате HEX', max_length=7, validators=[django.core.validators.RegexValidator(message='Необходимо указать цвет в кодировке HEX.', regex='#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
