# Generated by Django 4.2.5 on 2023-10-10 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Время приготовления: не меньше 1 мин.')], verbose_name='время приготовлениия'),
            preserve_default=False,
        ),
    ]
